### PR TITLE
Rtems test

### PR DESCRIPTION
**Pull request by anjohnson**
Testing the rtems-test changes...

### CODE REVIEW

**Comment by anjohnson** [comment]
@mdavidsaver The RTEMS 4.9 build failed twice on Travis; I just retriggered [the build](https://travis-ci.org/epics-base/epics-base/jobs/445989521) and got exactly the same fault.

The build failure is due to a build rule:
```
rm -f temp.bin
rm -f temp.bin
/home/travis/.rtems/bin/i386-rtems4.9-objcopy -O binary -R .comment -S analogMonitorTest temp.bin
/home/travis/.rtems/bin/i386-rtems4.9-objcopy -O binary -R .comment -S scanEventTest temp.bin
/home/travis/.rtems/i386-rtems4.9/pc386/build-tools/bin2boot analogMonitorTest.boot 0x00097E00 /home/travis/.rtems/i386-rtems4.9/pc386/lib/start16.bin 0x00097C00 0 temp.bin 0x00100000 0
/home/travis/.rtems/i386-rtems4.9/pc386/build-tools/bin2boot scanEventTest.boot 0x00097E00 /home/travis/.rtems/i386-rtems4.9/pc386/lib/start16.bin 0x00097C00 0 temp.bin 0x00100000 0
rm -f temp.bin
/home/travis/.rtems/bin/i386-rtems4.9-objcopy -O binary -R .comment -S regressTest temp.bin
rm -f temp.bin
/home/travis/.rtems/i386-rtems4.9/pc386/build-tools/bin2boot regressTest.boot 0x00097E00 /home/travis/.rtems/i386-rtems4.9/pc386/lib/start16.bin 0x00097C00 0 temp.bin 0x00100000 0
unable to open output file temp.bin
```
Inside `CONFIG.Common.RTEMS-pc386` the definition of `MUNCH_CMD` is using the same temp.bin file for all munch operations, so when your tests build lots of .boot files in parallel there is munch confusion... :trombones:

I'm fixing this, and will merge if the result succeeds.

BTW something seems to be causing these warnings, any ideas? They seem benign though.
```
/home/travis/.rtems/bin/i386-rtems4.9-ar rc   libdbRecStdTest.a        asTestLib.o 
/home/travis/.rtems/bin/i386-rtems4.9-ranlib libdbRecStdTest.a
{standard input}: Assembler messages:
{standard input}:2534086: Warning: .stabs: description field '1026b' too big, try a different debug format
{standard input}:2534087: Warning: .stabs: description field '10273' too big, try a different debug format
{standard input}:2534088: Warning: .stabs: description field '10274' too big, try a different debug format
{standard input}:2534089: Warning: .stabs: description field '1027b' too big, try a different debug format
{standard input}:2534090: Warning: .stabs: description field '10283' too big, try a different debug format
{standard input}:2534091: Warning: .stabs: description field '10284' too big, try a different debug format
{standard input}:2534092: Warning: .stabs: description field '10296' too big, try a different debug format
{standard input}:2534093: Warning: .stabs: description field '1029e' too big, try a different debug format
{standard input}:2534094: Warning: .stabs: description field '1029f' too big, try a different debug format
{standard input}:2534095: Warning: .stabs: description field '102a9' too big, try a different debug format
{standard input}:2534096: Warning: .stabs: description field '102b1' too big, try a different debug format
{standard input}:2534097: Warning: .stabs: description field '102b2' too big, try a different debug format
{standard input}:2534098: Warning: .stabs: description field '102d0' too big, try a different debug format
{standard input}:2534099: Warning: .stabs: description field '102d8' too big, try a different debug format
{standard input}:2534100: Warning: .stabs: description field '102d9' too big, try a different debug format
{standard input}:2534101: Warning: .stabs: description field '13601' too big, try a different debug format
{standard input}:2534102: Warning: .stabs: description field '13609' too big, try a different debug format
{standard input}:2534103: Warning: .stabs: description field '1360a' too big, try a different debug format
{standard input}:2534104: Warning: .stabs: description field '1362f' too big, try a different debug format
{standard input}:2534105: Warning: .stabs: description field '13636' too big, try a different debug format
{standard input}:2534106: Warning: .stabs: description field '1363a' too big, try a different debug format
{standard input}:2534107: Warning: .stabs: description field '1363b' too big, try a different debug format
```

**Comment by mdavidsaver** [comment]
> unable to open output file temp.bin

Ha.  I keep meaning to fix this in configure/os/CONFIG.Common.RTEMS-pc386

**Comment by anjohnson** [comment]
Okay, I'm going to do the merge while Travis is finishing up, merging the Launchpad version of rtems-test into 3.16 rather than the other way around and cherry-picking your commits along the way.

Did you look at my final version of [dtypedset](https://code.launchpad.net/~epics-core/epics-base/+git/dtypedset/+merge/332730)?

**Comment by anjohnson** [comment]
Merged through Launchpad.

**Pull request closed without merging**
