### PR TITLE
Add missing AFTC field documentation

### LINKED ISSUE #313: Some record types are missing AFTC documentation
The AFTC field was added to 5 record types, but only 2 of them have it documented in their .dbd.pod files. Using those 2 as examples, a develop text for the other 3, adjusting the wording as appropriate.

### PR DESCRIPTION
**Pull request by henrique-silva**
Fixes #313 

Also added a missing paragraph describing the HYST field in longin

### CODE REVIEW

**Comment by simon-ess** [comment]
LGTM

**Comment by karlvestin** [comment]
I had a conversation with Andrew today about the AFTC field. The actual function of this field is somewhat weird, and not particularly well described by the documentation. I think it would make sense to add a statement in the documentation that this is primarily an internal value to implement HYST, and not of general user relevance.

**Comment by henrique-silva** [comment]
But as far as I can see from the code, it has nothing to do with the `HYST` field itself:
https://github.com/epics-base/epics-base/blob/d9052f71056ab38217344e0f6d395e6937f15965/modules/database/src/std/rec/aiRecord.c#L358-L400

It is a further calculation after the `HYST` check, but it is only used in conjunction with the very much undocumented field `AFVL`

**Comment by anjohnson** [comment]
IIRC our conversation was about the `LALM` field, I think Karl used the wrong field name in his comment above about it being an internal implementation detail.

This looks good to me, thanks!

**Review by anjohnson — APPROVED** [review]
Doc changes only.

**Comment by mdavidsaver** [comment]
Applied as of 5c9903115719dde7f265d5201d4f15d1a00938de

**Pull request closed without merging**
