### PR TITLE
Fixed .gitignore for git versions prior to 1.8.2

### PR DESCRIPTION
**Pull request by bhill-slac**
Changed **/O.* in submodule .gitignore files to O.*/ as it works for git versions before 1.8.2 as well as newer versions.

### CODE REVIEW

**Comment by bhill-slac** [comment]
Not sure if I did this right.   Trying to avoid creating a pull request for each submodule.

**Comment by anjohnson** [comment]
Hi Bruce, I don't think there *is* a right way to do this now with submodules, unfortunately. I currently have no way of seeing the changes you want in the submodules (the PR only gives the new sha of your local commits to those modules, but the commits themselves currently only exist on your machine), but I'm pretty sure they just involve replacing `**/O.*` with `O.*/` in the .gitignore files, which I will do. Please let me know if there was anything else.

**Comment by bhill-slac** [comment]
That's the only change I made.
Looks like one pull request per submodule is needed in the future.
Thanks!
- Bruce

**Comment by anjohnson** [comment]
Committing equivalent changes by another route.

**Pull request closed without merging**
