### PR TITLE
Enable Epics for RTEMS5 (posix)

### PR DESCRIPTION
**Pull request by hjunkes**

### CODE REVIEW

**Comment by mdavidsaver** [comment]
I spent some time on this.  The [result](https://github.com/mdavidsaver/epics-base/tree/rtems5) builds and passes test with RTEMS 4.9 and 4.10.  It builds for RTEMS 5.1.  I am able to run some of the tests, but there are some hangs.  The first I've looked into is epicsTimeTest, which seems to hang when leaving a c++ `catch(...){`.  The actual hang seems to be a tight loop in the `__atomic_fetch_add_4` GCC builtin.  Looking though my old email, I find https://devel.rtems.org/ticket/2830 which is still unresolved.

This seems like a deal breaker for RTEMS 5.1 and i386 as far as EPICS is concerned.

The only reason I care about i386/pc686 is as a way for CI runners to execute unittests w/ unmodified QEMU.  I would be happy to have an alternative recipe.  Preferably one which is usable with 4.x as well, though I appreciate that this may not be feasible given the state of ARM support in the 4.9 series.

**Comment by mdavidsaver** [comment]
Building for the mvme3100 BSP fails since the `HAVE_MOTLOAD` case in setBootConfigFromNVRAM.c is trying to access the now unavailable `rtems_bsdnet_config`.  The `HAVE_PPCBUG` case needs fixing as well.

Also, I really don't like adding a second copy of setBootConfigFromNVRAM.c.  One is already a more than enough mess.

That's enough for me today.

**Comment by mdavidsaver** [comment]
Really last thing this time.  The buggy version of epicsMessageQueue.c is being re-added, so epicsMessageQueueTest fails.  Also, the windows/mingw jobs are failing because of missing `-DBUILDING_...`.  I'm not sure why.

**Comment by mdavidsaver** [comment]
There has been progress on the [i386 issue](https://devel.rtems.org/ticket/2830).  I'm now able to run all tests very slowly with QEMU.  There is a ~50 second delay during the network setup phase of each test run.  There are a couple of failures.  I haven't look in detail, but I suspect they are not major.

```
epicsEnvUnsetTest.tap ........ 1/? 
not ok  3 - TEST_VAR_A = "test value"
epicsEnvUnsetTest.tap ........ Failed 1/3 subtests 
...
osiSockTest.tap .............. 1/? 
not ok 19 - Found non-loopback interface
not ok 20 - Successes 0
osiSockTest.tap .............. Failed 2/24 subtests 
```

**Comment by hjunkes** [comment]
Wow, that's good news. I'll try to look at it next week. This can only be a small thing when setting up the dhcpcd and setting of the "boot" variables.
(Unfortunately I had to take a break. I was busy with administration, preparing the meeting and writing "politic" proposals.)

**Comment by hjunkes** [comment]
> There has been progress on the [i386 issue](https://devel.rtems.org/ticket/2830). I'm now able to run all tests very slowly with QEMU. There is a ~50 second delay during the network setup phase of each test run. There are a couple of failures. I haven't look in detail, but I suspect they are not major.
> 
> ```
> epicsEnvUnsetTest.tap ........ 1/? 
> not ok  3 - TEST_VAR_A = "test value"
> epicsEnvUnsetTest.tap ........ Failed 1/3 subtests 
> ...
> osiSockTest.tap .............. 1/? 
> not ok 19 - Found non-loopback interface
> not ok 20 - Successes 0
> osiSockTest.tap .............. Failed 2/24 subtests 
> ```

Is it with the legacy stack or with libbsd ?

**Comment by mdavidsaver** [comment]
> Is it with the legacy stack or with libbsd ?

Not that I'm aware.  How can I tell?

**Comment by hjunkes** [comment]
You use libbsd ;-) Unfortunately I still have the problem with the rtems_libio_iops. 
/home/h1/DBG/rtems/lib/gcc/i386-rtems5/7.5.0/../../../../i386-rtems5/bin/ld: /home/h1/DBG/dev/rtems-source-builder/rtems/build/i386-rtems5-kernel-pc686-1/i386-rtems5-kernel-pc686-1-61ccb9c05dcd695114541960aa6bfc1315f30514/rtems-61ccb9c05dcd695114541960aa6bfc1315f30514/cpukit/include/rtems/score/cpustdatomic.h:369: undefined reference to `rtems_libio_iops'
I still have to go through the rtems techtalk. I think I've seen that before.

**Comment by hjunkes** [comment]
Arghh, stupid typo:
diff --git a/configure/os/CONFIG.Common.RTEMS b/configure/os/CONFIG.Common.RTEMS
index 61512af84..ec2d5ad82 100644
--- a/configure/os/CONFIG.Common.RTEMS
+++ b/configure/os/CONFIG.Common.RTEMS
@@ -114,7 +114,7 @@ endif
 OP_SYS_CFLAGS += -D__LINUX_ERRNO_EXTENSIONS__
 ifeq ($(RTEMS_API),5)
 #OP_SYS_LDLIBS += -lrtemsCom -lrtemscpu -lrtemsbsp -ltftpfs -ltelnetd -lbsd -lz -lm
-Ot_SYS_LDLIBS += -lrtemsCom -lc -lrtemscpu  -ltftpfs -lbsd -lz -lm
+OP_SYS_LDLIBS += -lrtemsCom -lc -lrtemscpu  -ltftpfs -lbsd -lz -lm
 else
 OP_SYS_LDLIBS += -lrtemsCom -lc -lrtemscpu -lrtemsCom -lCom -lnfs -lm
 endif

**Comment by anjohnson** [comment]
Superseded by #105

**Pull request closed without merging**
