### PR TITLE
libCom: test osdSockAddrReuse

### PR DESCRIPTION
**Pull request by mdavidsaver**
Ensure that `epicsSocketEnableAddressReuseDuringTimeWaitState()` and `epicsSocketEnableAddressUseForDatagramFanout()` have the desired effects.

### CODE REVIEW

**Comment by mdavidsaver** [comment]
This change only adds to the `osiSockTest` unittest.  However, it is changed in a way which violates the principle of test isolation by attempting to send (properly formatted) CA search messages to all local interface broadcast addresses.  So there is some risk of external side-effects.  However, I think this risk is low, and offset by the benefit of hopefully detecting regressions in this OS dependent code.

The test is still not passing on travis-ci `os: trusty`, though I think this is due to VM network configuration.

**Comment by mdavidsaver** [comment]
I've (re)discovered that the broadcast address is mis-configured on the trusty VM image.

```
eth0      Link encap:Ethernet  HWaddr 42:01:0a:14:00:66  
          inet addr:10.20.0.102  Bcast:10.20.0.102  Mask:255.255.255.255
          UP BROADCAST RUNNING MULTICAST  MTU:1460  Metric:1
          RX packets:13709 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10715 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:237955857 (237.9 MB)  TX bytes:950413 (950.4 KB)
```

**Comment by anjohnson** [comment]
I have no objections to the spamming behavior. I assume you've checked it with an IOC running and it doesn't trigger anything (other than the usual silent name-search). Will the test still pass if it gets a reply from an IOC that actually has a matching named PV?

**Comment by mdavidsaver** [comment]
> I assume you've checked it with an IOC running

I've checked with a softIoc, and also snooped with wireshark to see that the search is properly formatted.  Though I should note that the search being sents protocol version 0 in the header, which newer servers will ignore out of hand.  The payload is just the PV name though, with proper alignment.

> reply from an IOC

The test is not looking at replies.  It will see other searches, which it will ignore.

**Comment by mdavidsaver** [comment]
Unless further concerns raised in the next day or so, I'll consider this accepted.

**Comment by ralphlange** [comment]
Fine with me.

**Pull request merged**
