### PR TITLE
Create implicit leak

### PR DESCRIPTION
**Pull request by FreddieAkeroyd**
Continuation of work started by @mdavidsaver in https://github.com/epics-base/epics-base/pull/240

### CODE REVIEW

**Comment by mdavidsaver** [comment]
Looks ok at a glance.  Now we wait for appveyor...

**Comment by FreddieAkeroyd** [comment]
I think that is all done - I did have a go at a rebase and squash but it didn't like something, so i'll leave it for whoever does the PR merge to squash etc.

**Comment by mdavidsaver** [comment]
Looks ok to me.  The new comments at the top do clarify the situation.

**Comment by mdavidsaver** [comment]
Since the appveyor runs passed I'm going to mark this approved.  @anjohnson or @ralphlange, go ahead and remove the tag if you are planning to look at this (again).

**Comment by mdavidsaver** [comment]
Applied as f56412d6a56226524be57620f00b63519638b6aa

**Pull request closed without merging**
