### PR TITLE
dbLoadTemplate: error propagation

### PR DESCRIPTION
**Pull request by mdavidsaver**
Propagate `dbLoadDatabase()` errors out from `dbLoadTemplate()`.  Also print more meaningful error messages.

Seems straightforward enough to me, although failing earlier is a behavior change.

### CODE REVIEW

**Comment by anjohnson** [comment]
Makes sense to me. Should the error message(s) be using the color macros or are they included in the `yyerror()` output already?

**Comment by mdavidsaver** [comment]
`yyerror()` does prefix `ERL_ERROR`.

**Comment by anjohnson** [comment]
LGTM then.

**Comment by mdavidsaver** [comment]
> LGTM then.

I will consider this approved then.

**Comment by mdavidsaver** [comment]
Merged as 1cd141c540c5532f1618c538c3a81a62fc73c639

**Pull request closed without merging**
