### PR TITLE
editorconfig: add initial version forcing final newlines

### PR DESCRIPTION
**Pull request by minijackson**
As per comment https://github.com/epics-base/epics-base/pull/337#issuecomment-1458388011

CC @anjohnson 

This file may be extended later if we want to enforce tabs / space length by filetype.

### CODE REVIEW

**Comment by minijackson** [comment]
If I remember correctly, there is the possibility of adding a GitHub action that checks that the EditorConfig file is upheld in the codebase, I'll add it in this PR in a bit.

**Comment by minijackson** [comment]
There we go! It should work now.

**Comment by anjohnson** [comment]
This looks great to me (and Ralph)!

**Comment by mdavidsaver** [comment]
Just to note, this PR adds a 3rd party github action.  At the moment, the repository policy allows any action.  I don't see an issue since we don't currently have any secrets associated with this repo.

**Comment by anjohnson** [comment]
I did see a note on another repo recently where the project's maintainer explicitly specified the SHA of the 3rd party action script instead of its version number. The owner of that action could move the version tag at a later date but couldn't (easily) change the commit with that SHA to add anything malicious. Is it worth our adopting that convention?

**Comment by mdavidsaver** [comment]
Applied as of c7a769e5da9ce7253e58a321e2fd7e0da1ba8cf3

**Pull request closed without merging**
