### PR TITLE
Test  and fix DB link DBF_MENU to DBF_STRING

### PR DESCRIPTION
**Pull request by mdavidsaver**
Add test to demonstrate #183.  No fix yet.

### CODE REVIEW

**Review by anjohnson — APPROVED** [review]
Good solution, thanks!

**Comment by mdavidsaver** [comment]
Note that the added test case has a TODO since this change does not effect CA links, where `DBF_MENU -> DBF_STRING` still doesn't work.

**Comment by mdavidsaver** [comment]
Applied as of 7ce69155a9736ab02ea1265901c55d9044a19350

**Comment by ralphlange** [comment]
FYI
We're seeing a test failure of the added regression test:
```
/home/build/workspaces/trunk/m-epics/target/base-7.0.6.1/modules/database/test/std/rec/O.linux-x86_64
...
regressTest.t ...........
not ok 54 - dbGetField("li2", 5) -> 3 == 0
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/54 subtests
```

**Comment by mdavidsaver** [comment]
I take it your test runner isn't setup to capture core dumps?  The only other occurrence I've seen so far (probably) was from a windows build which didn't produce a meaningful stack trace.

cf. https://github.com/epics-base/epics-base/discussions/162#discussioncomment-1614969

**Comment by ralphlange** [comment]
Happened again yesterday. I will try to set up core dump capture.

**Pull request closed without merging**
