### PR TITLE
Add diagnostic support for showing record values when TPRO is >= 2

### PR DESCRIPTION
**Pull request by bhill-slac**

### CODE REVIEW

**Comment by anjohnson** [comment]
Not sure that I like overloading TPRO like this; Eric Norum would probably call it a Camel's Nose issue.

Does anyone else think this is a good idea?

**Comment by ralphlange** [comment]
I know at least three Device Supports where TPRO > 1 is used to switch on debugging (TPRO being verbosity) for specific records. Which is very handy.

We have to be careful with defining things that were undefined for decades. This deserves at least a call on Tech Talk to warn people, and maybe a definition that allows both record support and device support to share the field.

**Comment by bhill-slac** [comment]
I don't see a conflict here.   We're already sharing TPRO between record support and several device support modules, 
with larger values of TPRO enabling more verbose diagnostic output.

Note that this change does not affect how TPRO propagates. i.e.   Propagated TPRO via plockSet->trace is still 1, so to 
get more verbose diagnostics for a particular record you have to set TPRO >= 2 for that record.

**Comment by bhill-slac** [comment]
Closing pull request.   Please see:
https://code.launchpad.net/~bhill/epics-base/+git/epics-base/+merge/341081

**Pull request closed without merging**
