### PR TITLE
Add de-initHooks

### PR DESCRIPTION
**Pull request by mdavidsaver**
Extend the initHook idea to `exitDatabase()`.

### CODE REVIEW

**Comment by anjohnson** [comment]
Seems reasonable. My only request would be to expand slightly on the one-word "conditional" comment against the state definitions to say what the condition is. I'd like to avoid complaints or questions from external module authors when those hooks don't get fired at shutdown in a regular IOC; they shouldn't have to search the code to see what that condition is.

**Comment by mdavidsaver** [comment]
Would "conditional.  testIocShutdownOk() only" be sufficient?

**Comment by anjohnson** [comment]
Something like "triggered only by self-test code" would address the somewhat wider audience I'm thinking about; the word "conditional" isn't very enlightening here.

**Comment by anjohnson** [comment]
Approve.

**Comment by mdavidsaver** [comment]
> Approve.

Noted.  FYI. github has a way to record this [more prominently](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/reviewing-proposed-changes-in-a-pull-request).

**Review by anjohnson — APPROVED** [review]
I was aware this is possible, but they don't make the approval process as easy as it could be – you have to know how to get the website to put up the button.

**Comment by mdavidsaver** [comment]
Cherry picked as 5d5e552a7ec6ef69459c97b0081aa775372a6290

**Pull request closed without merging**
