### PR TITLE
Fix miscellaneous issues found by static code analysis

### PR DESCRIPTION
**Pull request by ralphlange**
This PR is fixing a handful of issues that were found by static code analysis (cppcheck/sonar).

Admittedly, some cppcheck complaints seemed a bit far fetched, but there's something to all of the issues I fixed and the fixes seem reasonable and sane. (To me, that is.)
I strictly only fixed the issues necessary for EPICS Base to move from failing the ITER Sonar checks to passing them.

### CODE REVIEW

**Comment by ralphlange** [comment]
This PR was originally done on 7.0 and manually rebased (via format-patch) to 3.15.
I still have the original equivalent branch, in case I should rather do another PR against 7.0 instead of upmerging the changes.

**Comment by ralphlange** [comment]
Sorry about that - had missed one.

**Review by mdavidsaver — APPROVED** [review]
This all looks straightforward to me.

**Review by anjohnson — APPROVED** [review]
These look fine to me.

**Comment by ralphlange** [comment]
Ok, I'll go ahead and merge.
@anjohnson: Separate PR for 7.0 or later upmerge?

**Comment by anjohnson** [comment]
Michael said he was able to up-merge with a suitable git configuration; maybe the person doing the 3.15 merge could also do the up-merge to 7.0?

I think we either have to keep doing them or stop completely, it doesn't work if some commits get up-merged and others don't since the next up-merge following the merge of a change with separate PRs will include the changes from the older branch that will conflict with the changes from the later PR. @mdavidsaver please correct me if this is wrong.

**Comment by ralphlange** [comment]
I'd be willing to try the upmerge myself, if there's a description of the process somewhere.
(I could also create such a recipe from a rough handwritten description.)

**Comment by anjohnson** [comment]
Back when we had 4 separate submodule branches for Base I wrote myself a gist which I'd completely forgotten about until I was about to post the text below. [This section](https://gist.github.com/anjohnson/4344d3ed541f5af27e493aebd68cb3df#merging-up-into-base-70) might still have some useful stuff in the `git mv` commands, but I only just wrote the text below.

For up-merges which don't add any new files doing one is roughly:

```bash
$ make distclean
$ git checkout 7.0
$ git fetch origin
$ git pull
$ git merge --no-commit origin/3.15
$ make -sj
$ make -s runtests
$ git commit -m 'Merge changes from 3.15 branch'
$ git push origin 7.0
```

However you should first apply the `.git/config` or `~/.gitconfig` setting which @mdavidsaver posted and which I seem to have since lost (I did find and use that `git merge` option for some earlier up-merges, but apparently only on the command-line).

If you're very lucky the `git merge` command will complete with no conflicts and you just have to check that it builds, commit and push the result. I usually replace the log text provided because we really don't need to keep a record of what you name your 'origin' remote. For some reason when Michael does up-merges his log messages even include the commented-out conflict lines which `git commit` normally strips out – I guess they could be useful evidence for later investigations into issues with a bad merge, but I don't see them as necessary.

If you get conflicts but it found the right file you just need to fix them as appropriate. However if git can't work out what file to apply the changes to that's when it starts to get annoying. I have previously used `patch -p1` to apply larger sets of changes, fixing up the diff for individual hunks as necessary. This can be a pain though, suggestions of better tools to help with this step would be helpful.

When there are new files added you have to work out where they are supposed to go in the new layout and fix up the Makefiles to match (sometimes the additions to them merge up nicely, but not always).

Before you do finally commit the merge, please double-check that it didn't add files to directories that we previously moved elsewhere, and do the `make distclean; make; make runtests` to ensure that everything builds happily and passes tests on at least your host-arch. Travis & Appveyor should soon help with other arch's.

**Comment by mdavidsaver** [comment]
@anjohnson Run this now before you forget again.

```sh
git config --global diff.renamelimit 0
```

> For some reason when Michael does up-merges his log messages even include the commented-out conflict lines

I don't pass `--no-commit` to `git merge`.  Even not so recent git is able to amend merge commits.  So I record the merge commit immediately after resolving conflicts, and before doing a test build.  This avoids some possibilities of my messing up and having to redo the merge.

**Comment by anjohnson** [comment]
> git config --global diff.renamelimit 0

Thanks, done.

`git add` is your friend; once you've done that as long as your "messing up" doesn't destroy your .git directory git knows what source code changes you recorded in the index and it can reproduce that version for you (or commit it). However `git commit --amend` works fine too.

**Pull request merged**
