### PR TITLE
Add SIMM=RAW to ao records

### PR DESCRIPTION
**Pull request by daykin**
resolves https://bugs.launchpad.net/epics-base/+bug/1712363

### CODE REVIEW

**Comment by anjohnson** [comment]
Ping @ralphlange please review.

**Comment by ralphlange** [comment]
This looks good.
I will broaden the PR scope a bit and add SIMM=RAW support for the other applicable record types.

**Comment by ralphlange** [comment]
@daykin : Would you mind looking at what I did?

**Comment by daykin** [comment]
> @daykin : Would you mind looking at what I did?

Everything makes sense to me.

**Pull request merged**
