### PR TITLE
No double-colon rules

### PR DESCRIPTION
**Pull request by anjohnson**
This is my preferred approach, which avoids the double-colon rules but should be just as flexible. It will probably need some refining, but includes the enhanced test-results rule that I was working on.

### CODE REVIEW

**Comment by anjohnson** [comment]
See https://ci.appveyor.com/project/anjohnson/epics-base/builds/32325246 for my Appveyor build.

**Comment by ralphlange** [comment]
Not having heard from you, I was also working on a branch ... will rebase on your if necessary.
Thanks!

**Comment by ralphlange** [comment]
With that narrowing of the static pattern rules for %tap and %xml resulting from perl tests, this works fine for my Google Test integration.
Thanks a lot!!

**Comment by ralphlange** [comment]
Don't worry about the force push - I was solely removing my last commit of yesterday which was heading off into the wrong direction. (And that was not in this branch.)

**Comment by mdavidsaver** [comment]
I still find myself `clean::ing` up after the last such change, so my first concern is avoiding a repetition.  In this instance I think such a change is acceptable, if only because unittests are still so rare in EPICS modules.

The only other such rule left seems to be `show-makefiles::`.

**Comment by ralphlange** [comment]
This branch by Andrew is reverting my change (introducing double::rules) that I did just a few days ago. No side effects on other base or user code.

**Comment by anjohnson** [comment]
As Ralph said my change undoes one of his from a few days earlier; I don't know of anyone else who was making use of the original single-colon target but if they were this means they would no longer have to make any changes.

The `show-makefiles::` rule is an internal one that I wouldn't expect any other module to be implementing or for us to ever need to change.

I will be merging this branch hopefully sometime today, once I get to the bottom of my Inbox.

**Pull request merged**
