### PR TITLE
Add "extern C" for many C headers

### PR DESCRIPTION
**Pull request by gabrielfedel**
I've tried to cover all C headers without extern C.
This allow that these files could be imported to C++ correctly.

### CODE REVIEW

**Comment by gabrielfedel** [comment]
I haven't changed header files with inline functions, If I understood correctly these functions should work correctly on C++.

**Comment by mdavidsaver** [comment]
The headers epicsMemFs.h epicsRtemsInitHooks.h osdVME.h osdSock.h and yajl_* are public, so an extern C is a needed.  The others are (I think) internal, where it does not harm.  All in all, looks fine to me.

> inline functions ... should work correctly on C++.

Yes for `static inline`.  Not for plain `inline`, but then we shouldn't have any of these in headers includeable by both C and C++ as it has different effects in these two languages.

**Comment by gabrielfedel** [comment]
@mdavidsaver Is there some standard to know if a header is internal or not? 

If you or anyone else think is necessary I can change the commit to remove the extern C from internal code.

**Comment by mdavidsaver** [comment]
>  if a header is internal or not?

Public headers are those which appear under `include/` after `make` has finished.  These will also have `INC += blah.h` entry in a Makefile.

**Comment by mdavidsaver** [comment]
Applied as 6feb1c788d261376d3b14440d0ce2114b3f6acd6

**Pull request closed without merging**
