### PR TITLE
Fix a bug which causes timers to expire early on modern Linux systems

### LINKED ISSUE #106: Timers expire early
Generally, timers are supposed to sleep for _at least_ the amount of time they were set for. However, the current EPICS timer implementation behaves differently:
```
# Testing timer accuracy
ok  2 - timerCount == nTimers
ok  3 - 0.486553 < 5.000000, delay = 1.000000 s, error = -0.004866 s (0.5 %)
ok  4 - 0.440644 < 5.000000, delay = 1.100000 s, error = -0.004847 s (0.4 %)
ok  5 - 0.404795 < 5.000000, delay = 1.200000 s, error = -0.004858 s (0.4 %)
ok  6 - 0.373543 < 5.000000, delay = 1.300000 s, error = -0.004856 s (0.4 %)
ok  7 - 0.346924 < 5.000000, delay = 1.400000 s, error = -0.004857 s (0.3 %)
ok  8 - 0.326921 < 5.000000, delay = 1.500000 s, error = -0.004904 s (0.3 %)
ok  9 - 0.303757 < 5.000000, delay = 1.600000 s, error = -0.004860 s (0.3 %)
ok 10 - 0.285826 < 5.000000, delay = 1.700000 s, error = -0.004859 s (0.3 %)
ok 11 - 0.270031 < 5.000000, delay = 1.800000 s, error = -0.004861 s (0.3 %)
ok 12 - 0.255543 < 5.000000, delay = 1.900000 s, error = -0.004855 s (0.3 %)
ok 13 - 0.242964 < 5.000000, delay = 2.000000 s, error = -0.004859 s (0.2 %)
ok 14 - 0.231398 < 5.000000, delay = 2.100000 s, error = -0.004859 s (0.2 %)
ok 15 - 0.220428 < 5.000000, delay = 2.200000 s, error = -0.004849 s (0.2 %)
ok 16 - 0.211106 < 5.000000, delay = 2.300000 s, error = -0.004855 s (0.2 %)
ok 17 - 0.202014 < 5.000000, delay = 2.400000 s, error = -0.004848 s (0.2 %)
ok 18 - 0.194164 < 5.000000, delay = 2.500000 s, error = -0.004854 s (0.2 %)
ok 19 - 0.186316 < 5.000000, delay = 2.600000 s, error = -0.004844 s (0.2 %)
ok 20 - 0.181187 < 5.000000, delay = 2.700000 s, error = -0.004892 s (0.2 %)
ok 21 - 0.173014 < 5.000000, delay = 2.800000 s, error = -0.004844 s (0.2 %)
ok 22 - 0.167593 < 5.000000, delay = 2.900000 s, error = -0.004860 s (0.2 %)
ok 23 - 0.163954 < 5.000000, delay = 3.000000 s, error = -0.004919 s (0.2 %)
ok 24 - 0.156422 < 5.000000, delay = 3.100000 s, error = -0.004849 s (0.2 %)
ok 25 - 0.152041 < 5.000000, delay = 3.200000 s, error = -0.004865 s (0.2 %)
ok 26 - 0.149199 < 5.000000, delay = 3.300000 s, error = -0.004924 s (0.1 %)
ok 27 - 0.142764 < 5.000000, delay = 3.400000 s, error = -0.004854 s (0.1 %)
# average timer delay error -4.863972 ms
```
Note how the timers are consistently expiring ~5 ms early (I ran this on a state-of-the-art Linux system). Turns out for some esoteric reason half a quantum is subtracted in `timer::privateStart()`. If other architectures require this adjustment it should probably only be applied to these architectures or alternatively the quantum should return 0 on modern Linux systems. The existing tests do not fail since they have a very generous tolerance of +/-5% (-0% +5% would probably be a better choice).

Related issues have been discussed in the past (see [here](https://epics.anl.gov/core-talk/2019/msg00520.php) and [here](https://epics.anl.gov/tech-talk/2008/msg00987.php)) without any action taken. Considering the significant error and the popularity of Linux machines in the EPICS community I think this issue deserves to be addressed.

### PR DESCRIPTION
**Pull request by mark0n**
Fixes #106. Tested on
- [X] Linux
- [ ] Darwin
- [ ] VxWorks
- [ ] RTEMS

### CODE REVIEW

**Comment by mdavidsaver** [comment]
@mark0n It seems like you are doing CI development on your branch, which is triggering a lot of emails from github.  FYI. I usually do such work on a separate branch in my repositories to avoid this (often named `ci` or similar).

**Comment by mark0n** [comment]
@mdavidsaver sorry, I keep forgetting about these emails...

**Comment by mark0n** [comment]
OK, this should be ready for review. Note that this PR builds on top of #108 (the macro introduced here should also be used to adjust the tolerance of my new tests). Please let me know if you have better ideas for how and where to include `osdTimer.h`.

**Comment by mark0n** [comment]
Superseded by #145.

**Pull request closed without merging**
