### PR TITLE
stripped-down fix for 1816841 only

### PR DESCRIPTION
**Pull request by till-s**
As requested - here's a (preliminary!) fix for bug 1816841 only

### CODE REVIEW

**Comment by till-s** [comment]
The travis build that failed seems completely unrelated to this pull-request...

**Comment by mdavidsaver** [comment]
Looks good, and definitely meets my definition of "simpler/smaller fix".

I've manually triggered the build with the failing test to re-run.

**Comment by mdavidsaver** [comment]
The appveyor queue is running about 3 days behind.  So my only immediate interest is in the travis-ci tests.

**Comment by mdavidsaver** [comment]
Something about this change has been bothering me.  The current implementation is clearly wrong.  If I revert the fix, then the new fest fails with:

```
1..2
not ok  1 - 'createImplicit' assigned correct priority (-1) to non-EPICS thread
ok  2 - epicsEventWait returned 0
```

However, the fix seems to carry some Linux specific assumptions which I suspect will need to be addressed in #23 and or #24.

For the present (impending 7.0.2.1) this is good enough.

**Comment by till-s** [comment]
Not sure I understand. The fix only attempts to compute an OSI priority if the non-epics thread which is implicitly being converted to an EPICS thread uses SCHED_FIFO. Otherwise the OSI priority is not computed, i.e., set to zero which is also what happens if the user disabled real-time scheduling in the configuration (DONT_USE_POSIX_THREAD_PRIORITY_SCHEDULING).

````
if ( pcommonAttr->usePolicy && pthreadInfo->schedPolicy == pcommonAttr->schedPolicy ) {
  /* compute OSI priority from OSS, assuming SCHED_FIFO */
````
`usePolicy` indicates whether pcommonAttr->schedPolicy is valid (which implies that it equals SCHED_FIFO)

**Pull request merged**
