### PR TITLE
Com: Adjust epicsAtomic conditionals for GCC

### PR DESCRIPTION
**Pull request by mdavidsaver**
cf. https://bugs.launchpad.net/epics-base/+bug/1932118

@dirk-zimoch fyi.

### CODE REVIEW

**Comment by anjohnson** [comment]
Thanks for the sorely needed explanatory comments.

An aside, but I discovered recently that the preprocessor’s `defined()` function is only actually valid when it appears directly inside a `#if` statement, although gcc and most other compilers have always allowed it in macros that get expanded in one. Recent versions of clang actually warn about UB when they see that, although they do still honor it.

**Comment by mdavidsaver** [comment]
Now that 7.0.6 is out the door, I'd like to merge this.

**Comment by mdavidsaver** [comment]
Core meeting review: acceptable

**Comment by anjohnson** [comment]
Working on CLANG version, race to who gets to merge it first...

**Comment by anjohnson** [comment]
I'm not sure that all the macro magic that sets `GCC_ATOMIC_INTRINSICS_AVAIL_SYNC` is correct here, please don't merge.

I have a version with it fixed though (I think) and with the common-with-clang implementation too. I'm supposed to be on vacation this afternoon though (what's left of it) so it'll be sometime next week before I'm ready to push that.

**Comment by mdavidsaver** [comment]
Superseded by #192

**Pull request closed without merging**
